apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::078121091920:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1MY4JI8ADT1CB
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::078121091920:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-12T14:22:16Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1534"
  uid: c121a75a-6824-4784-9edb-5b83b8b65876
